name: Deploy frontend of the PMS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged  # Run with privileged access to Docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

    - name: Build Docker image
      run: docker build -t chathuratd007/pms_front .

    - name: Push Docker image
      run: docker push chathuratd007/pms_front:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged  # Run with privileged access to Docker

    steps:
    - name: Pull Docker image
      run: docker pull chathuratd007/pms_front:latest

    - name: Stop existing Docker container (if running)
      run: docker stop pms_front || true

    - name: Remove existing Docker container (if exists)
      run: docker rm pms_front || true

    - name: Run Docker container in production
      run: |
        docker run -d -p 3000:3000 chathuratd007/pms_front:latest
