name: Deploy frontend of the PMS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t chathuratd007/pms_front .

    - name: Push Docker image
      run: docker push chathuratd007/pms_front:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker image
      run: docker pull chathuratd007/pms_front:latest

    - name: Stop existing Docker container (if running)
      run: docker stop pms_front || true

    - name: Remove existing Docker container (if exists)
      run: docker rm pms_front || true

    - name: Run Docker container in production
      run: |
        docker run -d -p 80:80 --name pms_front chathuratd007/pms_front:latest
